
DROP TABLE IF EXISTS APP_USERS;
  
CREATE TABLE APP_USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  avatar_id VARCHAR(250) DEFAULT NULL
);
